spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000000
  mail:
    host: smtp.gmail.com
    port: 587
    username: proyecto.coder2022@gmail.com
    password: ndmekqepuawgalhu
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  data:
    mongodb:
      database: final
      host: localhost
      port: 27017
jwt:
  expiration: 60000
  secret: springbootjwtcoderhouse
server:
  port: 8080
