spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000000
  mail:
    username: proyecto.coder2022@gmail.com
    password: ndmekqepuawgalhu
  data:
    mongodb:
      database: final
      host: localhost
      port: 27017
jwt:
  expiration: 60000
  secret: springbootjwtcoderhouse
server:
  port: 8080
